{
 "title": "Just Task It",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Tasks Created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jti-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"task_events\" and\r\n    r.event_type == \"task_created\" and\r\n    r._field == \"standard_value\"\r\n  )\r\n  |> count(column: \"_value\")\r\n  |> group(columns: [])\r\n"
    }
   ]
  },
  {
   "title": "Total Tasks Completed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jti-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"task_events\" and\r\n    r.event_type == \"task_completed\" and\r\n    r._field == \"standard_value\"\r\n  )\r\n  |> count(column: \"_value\")\r\n  |> group(columns: [])\r\n"
    }
   ]
  },
  {
   "title": "Total Taks Uncompleted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jti-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"task_events\" and\r\n    r.event_type == \"task_uncompleted\" and\r\n    r._field == \"standard_value\"\r\n  )\r\n  |> count(column: \"_value\")\r\n  |> group(columns: [])\r\n"
    }
   ]
  }
 ]
}